import Localization from './models/Localization';

const translationsSeed: Record<'en' | 'vi', Record<string, string>> = {
  en: {
    welcome: "Welcome to Stuffy Supermarket",
    search_placeholder: "Search tech gear...",
    add_to_cart: "Add to Cart",
    view_details: "View Details",
    cart: "Cart",
    login: "Login",
    logout: "Logout",
    flash_sale: "Flash Sale Madness",
    flash_sale_desc: "Up to 50% OFF on selected tech gear. Don't miss out!",
    ends_in: "Ends in",
    category: "Category",
    all: "All",
    language: "Language",
    products: "Products",
    wishlist: "Wishlist",
    admin: "Admin",
    live: "Live",
    support: "Support",
    hi: "Hi",
    loading: "Loading...",
    no_description: "No description available.",
    all_products: "All Products",
    live_sync: "Live Sync",
    sort_newest: "Newest",
    sort_price_asc: "Price: Low to High",
    sort_price_desc: "Price: High to Low",
    sort_rating: "Top Rated",
    sort_popular: "Most Popular",
    min_price: "Min $",
    max_price: "Max $",
    clear_price: "Clear Price",
    ai_found_products: "AI found {count} matching products",
    ai_found_product: "AI found {count} matching product",
    other_products_dimmed: "Other products are dimmed",
    clear_filter: "Clear filter",
    no_products_found: "No products found",
    view_3d: "View in 3D AR",
    loading_3d: "Loading 3D Engine...",
    added_to_cart_toast: "Added {name} to cart!",
    add_now: "Add Now",
    back_to_shop: "Back to Shop",
    student_reviews: "Student Reviews",
    seller_info: "Seller Info",
    rating: "rating",
    view_shop: "View Shop",
    chat_now: "Chat Now",
    login_to_chat: "Please log in to chat with the seller.",
    custom_accent_color: "Custom Accent Color",
    select_variant: "Select Variant",
    out_of_stock: "Out of Stock",
    free_shipping_options: "Free Shipping Options",
    return_policy: "30-Day Return Policy",
    genuine_warranty: "Genuine Warranty",
    write_review: "Write a Review",
    login_to_review: "Please login first to review this product.",
    verified_buyer_only: "Only verified buyers who received this product can write a review.",
    rating_label: "Rating (1-5)",
    experience_label: "Your Experience",
    experience_placeholder: "Share details of your own experience with this product...",
    submit_review: "Submit Review",
    customer_reviews: "Customer Reviews",
    verified_buyer: "Verified Buyer",
    no_reviews_yet: "No reviews yet. Be the first to review this product!",
    people_also_viewed: "People also Viewed",
    ai_recommendation: "AI RECOMMENDATION",
    similar_products: "Similar Products",
    your_cart: "Your Cart",
    items: "items",
    item: "item",
    clear_cart: "Clear cart",
    cart_empty: "Your cart is empty",
    browse_catalogue: "Browse the product catalogue to add items.",
    scan_and_go: "Scan & Go",
    scan_qr_desc: "Scan this QR code with your phone to add products remotely.",
    pin: "PIN",
    session_pin: "Session PIN",
    verified_shop: "Verified Shop",
    carrier: "Carrier:",
    shipping: "Shipping:",
    free: "Free",
    shop_voucher_code: "Shop voucher code",
    apply: "Apply",
    applied: "Applied",
    order_summary: "Order Summary",
    subtotal: "Subtotal",
    shop_discounts: "Shop Discounts",
    wheel_discount: "Wheel Discount",
    platform_discount: "Platform Discount",
    shipping_discount: "Shipping Discount",
    coins_redeemed: "Coins Redeemed",
    tax: "Tax (0%)",
    shipping_total: "Shipping (Total)",
    total: "Total",
    spin_for_discount: "Spin for a discount",
    platform_voucher: "Platform voucher",
    redeem_stuffy_coins: "Redeem Stuffy Coins",
    available_label: "Available: ",
    proceed_to_checkout: "Proceed to Checkout",
    secured_by: "Secured by Apple Pay / Stripe.",
    secure_checkout: "Secure Checkout",
    step_of: "Step {step} of 2 - {name}",
    shipping_info: "Shipping Info",
    payment_details: "Payment Details",
    street_address: "Street Address",
    city: "City",
    postal_code: "Postal Code",
    country: "Country",
    continue_to_payment: "Continue to Payment",
    test_mode_notice: "Test Mode - Feel free to use dummy text for the card details. No actual charges will be made.",
    name_on_card: "Name on Card",
    card_number: "Card Number",
    expiry: "Expiry (MM/YY)",
    cvc: "CVC",
    back: "Back",
    pay: "Pay",
    processing_stripe: "Processing via Stripe...",
    spin_and_win: "Spin & Win",
    one_free_spin: "One free spin for your ${total} order!",
    better_luck: "Better luck next time!",
    you_got: "You got {label}!",
    you_save: "You save ${save} — new total ${total}",
    free_ship_applied: "Free shipping applied to this order!",
    free_item_applied: "A random item will be added to your cart for free!",
    spinning: "Spinning...",
    spin_now: "SPIN NOW — FREE!",
    close: "Close",
    skip: "Skip",
    apply_discount: "Apply discount",
    ai_support_welcome: "Hi there! I am the Stuffy AI Support. How can I help you today?",
    stuffy_ai_support: "Stuffy AI Support",
    thinking: "Thinking...",
    ask_stuffy_ai: "Ask Stuffy AI Support...",
    stuffy_customer_hub: "Stuffy Customer Hub",
    ai_copilot: "AI Copilot",
    shop_chat: "Shop Chat",
    auth_required: "Authentication Required",
    login_to_chat_desc: "Please log in to your account to message sellers directly.",
    select_shop_to_message: "Select a Shop to Message",
    no_active_shops: "No active shops available.",
    seller_store: "Seller Store",
    send_msg_start_conv: "Send a message to start the conversation!",
    message_shop_placeholder: "Message {name}...",
    profile_details: "Profile Details",
    change_password: "Change Password",
    my_orders: "My Orders",
    order_history: "Order History",
    address_book: "Address Book",
    account_settings: "Account Settings",
    loading_orders: "Loading your orders...",
    no_pending_orders: "No pending orders",
    no_purchase_yet: "Looks like you haven't made a purchase yet.",
    order_id: "Order ID",
    placed_on: "Placed on",
    show_less: "Show less",
    more_items: "more items",
    ship_to: "Ship to:",
    logistics: "Logistics:",
    view_shipping_label: "View Shipping Label",
    no_logistics_updates: "No logistics updates yet. Package is awaiting carrier pickup.",
    order_received: "Order Received",
    return_refund: "Return / Refund",
    escrow_released: "Payment Released to Seller",
    escrow_disputed: "Dispute Under Review",
    escrow_refunded: "Payment Refunded",
    no_saved_addresses: "No saved addresses yet",
    add_new_address: "Add New Address",
    edit_address: "Edit Address",
    phone: "Phone",
    set_as_default: "Set as default",
    default: "DEFAULT",
    save_changes: "Save Changes",
    current_password: "Current Password",
    new_password: "New Password",
    full_name: "Full Name",
    email_address: "Email Address",
    my_voucher_wallet: "My Voucher Wallet",
    vouchers_available: "available",
    expired: "Expired",
    claimed: "Claimed ✓",
    claim_now: "Claim Now",
    desc_banner: "Your premier destination for high-quality tech gear and workspace essentials. We offer authentic products, exclusive deals, and fast shipping.",
    mfe_modules: "Exclusive Deals",
    platform_tech: "Express Shipping",
    brand_badge: "TRUSTED BRAND",
    cooldown_msg: "AI on cooldown — retry in {seconds}s",
    ai_analyzing: "AI is analyzing...",
    ask_ai_placeholder: 'Ask AI: "Set up a home office"...',
    gemini_ai_suggestion: "Gemini AI suggestion",
    best_matches: "Best matches",
    too_fast: "Analyzing too fast! Please slow down.",
    ai_error: "AI Service Error",
    notifications: "Notifications",
    mark_all_read: "Mark all as read",
    no_new_notifications: "No new notifications",
    view_previous_notifications: "View previous notifications",
    login_to_claim: "Please login to claim vouchers",
    ship_badge: "Ship",
    off_badge: "OFF",
    ai_pick: "AI Pick",
    previous: "Previous",
    next: "Next",
    only_left: "Only {count} left!",
    try_different_category: "Try selecting a different category.",
    review_submitted_success: "Review submitted successfully!",
    failed_submit_review: "Failed to submit review",
    loading_product_data: "Loading Product Data...",
    product_not_found: "Product not found.",
    bundle_deal_desc: "Bundle Deal: Buy {minQty} or more items in this shop to get {value}{type} off!",
    addon_deal: "Special Add-on Deal",
    addon_deal_desc: "Buy this product and add these accessories at a discounted price:",
    price: "Price",
    stock: "Stock",
    select_variant_alert: "Please select a product variant first!",
    added_items_to_cart: "Added items to cart!",
    status_pending: "Pending",
    status_processing: "Processing",
    status_shipped: "Shipped",
    status_delivered: "Delivered",
    status_canceled: "Canceled",
    coins_discount: "Coins Discount",
    final_total: "Final Total",
    pay_amount: "Pay ${amount}",
    order_received_confirm: "Are you sure you received this order? Clicking yes will release funds to the seller.",
    refund_reason_prompt: "Please enter the reason for your Return/Refund request:",
    refund_request_success: "Refund request submitted successfully. Escrow funds locked.",
    order_received_success: "Order received confirmed! Payment released.",
    please_fill_fields: "Please fill all fields.",
    fill_shipping_alert: "Please fill all shipping fields.",
    fill_payment_alert: "Please fill all payment fields.",
    select_item_checkout_alert: "Please select at least one item to checkout!",
    order_placed_success: "🎉 Order placed successfully! Invoice created.",
    error_creating_invoice: "Error creating invoice: ",
    address_added_success: "Address added successfully!",
    address_updated_success: "Address updated successfully!",
    address_removed: "Address removed",
    home_label: "Home",
    work_label: "Work",
    other_label: "Other",
    add_address: "Add Address",
    edit_label: "Edit",
    delete_label: "Delete",
    update_label: "Update",
    cancel_label: "Cancel",
    profile_updated_success: "Profile updated successfully!",
    failed_update_profile: "Failed to update profile",
    password_changed_success: "Password changed successfully!",
    failed_change_password: "Failed to change password",
    please_fill_both_fields: "Please fill in both fields",
    shopee_guarantee: "Shopee Guarantee:",
    escrow_held: "Payment Held in Escrow",
    test_mode: "Test Mode",
    login_required: "Please login first",
    network_error: "Network error",
    login_profile_desc: "Please log in to view your profile and orders.",
    member: "Member",
    address_label: "Address Label",
    invalid_voucher: "Invalid voucher",
    welcome_back: "Welcome Back",
    create_account: "Create Account",
    dont_have_account: "Don't have an account? ",
    already_have_account: "Already have an account? ",
    sign_up: "Sign up",
    sign_in: "Sign in",
    auth_failed: "Authentication failed",
    scan_tap_desc: "Tap any product to add it to the cart on the connected device.",
    session: "Session",
    storefront_loading: "Loading shop storefront...",
    shop_not_found: "Shop Profile Not Found",
    shop_deactivated: "This seller store may have been deactivated or removed.",
    shopee_mall: "Shopee Mall",
    no_shop_desc: "No store description available.",
    chat_with_seller: "Chat with Seller",
    no_featured_products: "No featured products selected.",
    all_store_products: "All Store Products",
    no_products_yet: "This shop doesn't have any products listed yet.",
    wishlist_empty: "Your Wishlist is Empty",
    wishlist_empty_desc: "Browse products and tap the heart icon to save items you love.",
    my_wishlist: "My Wishlist",
    items_saved: "items saved",
    item_saved: "item saved",
    live_stream_loading: "Loading live stream player...",
    live_label: "LIVE",
    viewers: "viewers",
    host: "Host",
    pinned_deal: "PINNED DEAL",
    buy: "Buy",
    rose_gift: "Rose",
    heart_gift: "Heart",
    rocket_gift: "Rocket",
    insufficient_coins: "Insufficient coins balance! Earn more by shopping.",
    login_to_gift: "Please log in to send virtual gifts!",
    live_bag_title: "Live Specials Shop Bag",
    no_live_products: "No products linked to stream.",
    live_comments_title: "Live Comments",
    type_comment: "Type comment...",
    send_comment: "Send",
    gift_rose_desc: "sent a Rose!",
    gift_heart_desc: "sent a Heart!",
    gift_rocket_desc: "sent a Rocket!",
    live_welcome: "Welcome to Stuffy Live Stream! Chat politely.",
    live_welcome_desc: "Click the shopping bag icon below to view hot deals!",
    bot_comment_1: "Is this product still in stock?",
    bot_comment_2: "Just ordered 2 items! So excited!",
    bot_comment_3: "Does this shop ship to Hanoi?",
    bot_comment_4: "Highly recommended seller!",
    bot_comment_5: "Are there any vouchers for this stream?",
    bot_comment_6: "Wow, the discount is huge!",
    bot_comment_7: "Super beautiful design",
    bot_comment_8: "Which carrier handles shipping?",
    bot_comment_9: "GHN shipping is very fast here.",
    select_payment_method: "Select Payment Method",
    credit_card: "Credit Card (Stripe)",
    vietqr: "VietQR Bank Transfer (PayOS)",
    pay_vietqr: "Pay via VietQR",
    generating_qr: "Generating VietQR Payment Link...",
    origin: "Origin",
    coins: "Coins"
  },
  vi: {
    welcome: "Chào mừng đến với Stuffy Supermarket",
    search_placeholder: "Tìm kiếm đồ công nghệ...",
    add_to_cart: "Thêm vào giỏ",
    view_details: "Xem chi tiết",
    cart: "Giỏ hàng",
    login: "Đăng nhập",
    logout: "Đăng xuất",
    flash_sale: "Cơn lốc Flash Sale",
    flash_sale_desc: "Giảm đến 50% cho một số sản phẩm công nghệ. Đừng bỏ lỡ!",
    ends_in: "Kết thúc sau",
    category: "Danh mục",
    all: "Tất cả",
    language: "Ngôn ngữ",
    products: "Sản phẩm",
    wishlist: "Yêu thích",
    admin: "Quản lý",
    live: "Trực tiếp",
    support: "Hỗ trợ",
    hi: "Chào",
    loading: "Đang tải...",
    no_description: "Không có mô tả sản phẩm.",
    all_products: "Tất cả sản phẩm",
    live_sync: "Đồng bộ trực tiếp",
    sort_newest: "Mới nhất",
    sort_price_asc: "Giá: Thấp đến Cao",
    sort_price_desc: "Giá: Cao đến Thấp",
    sort_rating: "Đánh giá cao nhất",
    sort_popular: "Phổ biến nhất",
    min_price: "Tối thiểu $",
    max_price: "Tối đa $",
    clear_price: "Xóa giá",
    ai_found_products: "AI tìm thấy {count} sản phẩm phù hợp",
    ai_found_product: "AI tìm thấy {count} sản phẩm phù hợp",
    other_products_dimmed: "Sản phẩm khác đã bị ẩn đi",
    clear_filter: "Xóa bộ lọc",
    no_products_found: "Không tìm thấy sản phẩm",
    view_3d: "Xem ở chế độ 3D AR",
    loading_3d: "Đang tải mô hình 3D...",
    added_to_cart_toast: "Đã thêm {name} vào giỏ hàng!",
    add_now: "Mua ngay",
    back_to_shop: "Quay lại cửa hàng",
    student_reviews: "Đánh giá của sinh viên",
    seller_info: "Thông tin người bán",
    rating: "đánh giá",
    view_shop: "Xem cửa hàng",
    chat_now: "Chat ngay",
    login_to_chat: "Vui lòng đăng nhập để trò chuyện với người bán.",
    custom_accent_color: "Màu sắc tùy chỉnh",
    select_variant: "Chọn phiên bản",
    out_of_stock: "Hết hàng",
    free_shipping_options: "Miễn phí vận chuyển",
    return_policy: "Đổi trả trong 30 ngày",
    genuine_warranty: "Bảo hành chính hãng",
    write_review: "Viết đánh giá",
    login_to_review: "Vui lòng đăng nhập để đánh giá sản phẩm này.",
    verified_buyer_only: "Chỉ những khách hàng đã mua và nhận sản phẩm mới có thể đánh giá.",
    rating_label: "Đánh giá (1-5)",
    experience_label: "Trải nghiệm của bạn",
    experience_placeholder: "Chia sẻ trải nghiệm chi tiết của bạn về sản phẩm này...",
    submit_review: "Gửi đánh giá",
    customer_reviews: "Đánh giá của khách hàng",
    verified_buyer: "Người mua thực tế",
    no_reviews_yet: "Chưa có đánh giá nào. Hãy là người đầu tiên đánh giá sản phẩm này!",
    people_also_viewed: "Sản phẩm tương tự khách hàng cũng xem",
    ai_recommendation: "ĐỀ XUẤT AI",
    similar_products: "Sản phẩm tương tự",
    your_cart: "Giỏ hàng của bạn",
    items: "sản phẩm",
    item: "sản phẩm",
    clear_cart: "Xóa giỏ hàng",
    cart_empty: "Giỏ hàng của bạn đang trống",
    browse_catalogue: "Khám phá danh mục để thêm sản phẩm.",
    scan_and_go: "Quét & Đi",
    scan_qr_desc: "Quét mã QR bằng điện thoại để thêm sản phẩm từ xa.",
    pin: "Mã PIN",
    session_pin: "Mã phiên",
    verified_shop: "Cửa hàng uy tín",
    carrier: "Vận chuyển:",
    shipping: "Phí vận chuyển:",
    free: "Miễn phí",
    shop_voucher_code: "Mã voucher cửa hàng",
    apply: "Áp dụng",
    applied: "Đã áp dụng",
    order_summary: "Tóm tắt đơn hàng",
    subtotal: "Tạm tính",
    shop_discounts: "Khuyến mãi cửa hàng",
    wheel_discount: "Khuyến mãi vòng quay",
    platform_discount: "Khuyến mãi hệ thống",
    shipping_discount: "Giảm giá vận chuyển",
    coins_redeemed: "Đã đổi xu",
    tax: "Thuế (0%)",
    shipping_total: "Tổng phí vận chuyển",
    total: "Tổng cộng",
    spin_for_discount: "Quay để nhận giảm giá",
    platform_voucher: "Mã giảm giá hệ thống",
    redeem_stuffy_coins: "Dùng Xu Stuffy",
    available_label: "Đang có: ",
    proceed_to_checkout: "Tiến hành thanh toán",
    secured_by: "Thanh toán bảo mật qua Apple Pay / Stripe.",
    secure_checkout: "Thanh toán bảo mật",
    step_of: "Bước {step}/2 - {name}",
    shipping_info: "Thông tin giao hàng",
    payment_details: "Chi tiết thanh toán",
    street_address: "Địa chỉ chi tiết",
    city: "Tỉnh/Thành phố",
    postal_code: "Mã bưu chính",
    country: "Quốc gia",
    continue_to_payment: "Tiếp tục thanh toán",
    test_mode_notice: "Chế độ thử nghiệm - Bạn có thể điền thông tin thẻ giả. Sẽ không phát sinh giao dịch thực tế.",
    name_on_card: "Tên trên thẻ",
    card_number: "Số thẻ",
    expiry: "Hạn dùng (MM/YY)",
    cvc: "Mã bảo mật CVC",
    back: "Quay lại",
    pay: "Thanh toán",
    processing_stripe: "Đang xử lý qua Stripe...",
    spin_and_win: "Quay là Trúng",
    one_free_spin: "Một lượt quay miễn phí cho đơn hàng trị giá ${total}!",
    better_luck: "Chúc bạn may mắn lần sau!",
    you_got: "Bạn đã trúng {label}!",
    you_save: "Bạn tiết kiệm ${save} — tổng thanh toán mới ${total}",
    free_ship_applied: "Miễn phí vận chuyển cho đơn hàng này!",
    free_item_applied: "Một sản phẩm ngẫu nhiên sẽ được tặng kèm miễn phí!",
    spinning: "Đang quay...",
    spin_now: "QUAY NGAY — MIỄN PHÍ!",
    close: "Đóng",
    skip: "Bỏ qua",
    apply_discount: "Áp dụng giảm giá",
    ai_support_welcome: "Xin chào! Tôi là Trợ lý Hỗ trợ AI của Stuffy. Tôi có thể giúp gì cho bạn hôm nay?",
    stuffy_ai_support: "Hỗ trợ AI Stuffy",
    thinking: "Đang suy nghĩ...",
    ask_stuffy_ai: "Hỏi Trợ lý AI của Stuffy...",
    stuffy_customer_hub: "Trung tâm Khách hàng Stuffy",
    ai_copilot: "Trợ lý AI",
    shop_chat: "Trò chuyện Cửa hàng",
    auth_required: "Yêu cầu Đăng nhập",
    login_to_chat_desc: "Vui lòng đăng nhập vào tài khoản để nhắn tin trực tiếp cho người bán.",
    select_shop_to_message: "Chọn Cửa hàng để nhắn tin",
    no_active_shops: "Không có cửa hàng nào hoạt động.",
    seller_store: "Cửa hàng người bán",
    send_msg_start_conv: "Gửi tin nhắn để bắt đầu cuộc trò chuyện!",
    message_shop_placeholder: "Nhắn cho {name}...",
    profile_details: "Thông tin cá nhân",
    change_password: "Đổi mật khẩu",
    my_orders: "Đơn hàng của tôi",
    order_history: "Lịch sử mua hàng",
    address_book: "Sổ địa chỉ",
    account_settings: "Thiết lập tài khoản",
    loading_orders: "Đang tải đơn hàng...",
    no_pending_orders: "Không có đơn hàng nào",
    no_purchase_yet: "Có vẻ như bạn chưa thực hiện giao dịch nào.",
    order_id: "Mã đơn hàng",
    placed_on: "Đặt ngày",
    show_less: "Thu gọn",
    more_items: "sản phẩm khác",
    ship_to: "Giao đến:",
    logistics: "Vận chuyển:",
    view_shipping_label: "Xem phiếu giao hàng",
    no_logistics_updates: "Chưa có thông tin vận chuyển. Đang chờ đơn vị vận chuyển lấy hàng.",
    order_received: "Đã nhận hàng",
    return_refund: "Trả hàng / Hoàn tiền",
    escrow_released: "Thanh toán đã chuyển cho người bán",
    escrow_disputed: "Đang xem xét khiếu nại",
    escrow_refunded: "Đã hoàn tiền",
    no_saved_addresses: "Chưa có địa chỉ lưu trữ",
    add_new_address: "Thêm địa chỉ mới",
    edit_address: "Sửa địa chỉ",
    phone: "Số điện thoại",
    set_as_default: "Đặt làm mặc định",
    default: "MẶC ĐỊNH",
    save_changes: "Lưu thay đổi",
    current_password: "Mật khẩu hiện tại",
    new_password: "Mật khẩu mới",
    full_name: "Họ và tên",
    email_address: "Địa chỉ Email",
    my_voucher_wallet: "Ví Voucher Của Tôi",
    vouchers_available: "khả dụng",
    expired: "Đã hết hạn",
    claimed: "Đã nhận ✓",
    claim_now: "Nhận ngay",
    desc_banner: "Nơi mua sắm đồ công nghệ và thiết bị làm việc chất lượng hàng đầu. Chúng tôi cung cấp các sản phẩm chính hãng, ưu đãi độc quyền cùng dịch vụ giao hàng nhanh chóng.",
    mfe_modules: "Ưu đãi hấp dẫn",
    platform_tech: "Giao hàng siêu tốc",
    brand_badge: "THƯƠNG HIỆU UY TÍN",
    cooldown_msg: "AI đang hồi chiêu — thử lại sau {seconds} giây",
    ai_analyzing: "AI đang phân tích...",
    ask_ai_placeholder: 'Hỏi AI: "Cấu hình góc làm việc tại nhà"...',
    gemini_ai_suggestion: "Gợi ý từ Gemini AI",
    best_matches: "Sản phẩm khớp nhất",
    too_fast: "Đang phân tích quá nhanh! Vui lòng chậm lại.",
    ai_error: "Lỗi dịch vụ AI",
    notifications: "Thông báo",
    mark_all_read: "Đánh dấu tất cả là đã đọc",
    no_new_notifications: "Không có thông báo mới",
    view_previous_notifications: "Xem thông báo trước đó",
    login_to_claim: "Vui lòng đăng nhập để nhận voucher",
    ship_badge: "Vận chuyển",
    off_badge: "GIẢM",
    ai_pick: "AI Chọn",
    previous: "Trước",
    next: "Sau",
    only_left: "Chỉ còn {count} sản phẩm!",
    try_different_category: "Thử chọn danh mục khác xem sao.",
    review_submitted_success: "Đã gửi đánh giá thành công!",
    failed_submit_review: "Gửi đánh giá thất bại",
    loading_product_data: "Đang tải dữ liệu sản phẩm...",
    product_not_found: "Không tìm thấy sản phẩm.",
    bundle_deal_desc: "Mua chung: Mua từ {minQty} sản phẩm trở lên tại cửa hàng này để được giảm {value}{type}!",
    addon_deal: "Ưu đãi mua kèm đặc biệt",
    addon_deal_desc: "Mua sản phẩm này và thêm các phụ kiện sau với giá ưu đãi:",
    price: "Giá",
    stock: "Kho",
    select_variant_alert: "Vui lòng chọn phiên bản sản phẩm trước!",
    added_items_to_cart: "Đã thêm sản phẩm vào giỏ hàng!",
    status_pending: "Chờ xử lý",
    status_processing: "Đang xử lý",
    status_shipped: "Đang giao hàng",
    status_delivered: "Đã giao hàng",
    status_canceled: "Đã hủy",
    coins_discount: "Khuyến mãi xu",
    final_total: "Tổng thanh toán",
    pay_amount: "Thanh toán {amount}",
    order_received_confirm: "Bạn có chắc chắn đã nhận được đơn hàng này không? Xác nhận sẽ chuyển tiền thanh toán cho người bán.",
    refund_reason_prompt: "Vui lòng nhập lý do yêu cầu Trả hàng / Hoàn tiền:",
    refund_request_success: "Đã gửi yêu cầu hoàn tiền thành công. Số tiền giao dịch tạm thời bị khóa.",
    order_received_success: "Đã xác nhận nhận hàng! Tiền đã được chuyển cho người bán.",
    please_fill_fields: "Vui lòng điền đầy đủ các trường thông tin.",
    fill_shipping_alert: "Vui lòng điền đầy đủ thông tin giao hàng.",
    fill_payment_alert: "Vui lòng điền đầy đủ thông tin thanh toán.",
    select_item_checkout_alert: "Vui lòng chọn ít nhất một sản phẩm để thanh toán!",
    order_placed_success: "🎉 Đặt hàng thành công! Hóa đơn đã được tạo.",
    error_creating_invoice: "Lỗi tạo hóa đơn: ",
    address_added_success: "Thêm địa chỉ thành công!",
    address_updated_success: "Cập nhật địa chỉ thành công!",
    address_removed: "Đã xóa địa chỉ",
    home_label: "Nhà riêng",
    work_label: "Văn phòng",
    other_label: "Khác",
    add_address: "Thêm địa chỉ",
    edit_label: "Sửa",
    delete_label: "Xóa",
    update_label: "Cập nhật",
    cancel_label: "Hủy",
    profile_updated_success: "Cập nhật hồ sơ thành công!",
    failed_update_profile: "Không thể cập nhật hồ sơ",
    password_changed_success: "Đổi mật khẩu thành công!",
    failed_change_password: "Đổi mật khẩu thất bại",
    please_fill_both_fields: "Vui lòng điền vào cả hai trường",
    shopee_guarantee: "Shopee Đảm Bảo:",
    escrow_held: "Tạm giữ bởi hệ thống",
    test_mode: "Chế độ thử nghiệm",
    login_required: "Vui lòng đăng nhập trước",
    network_error: "Lỗi kết nối",
    login_profile_desc: "Vui lòng đăng nhập để xem thông tin hồ sơ và đơn hàng.",
    member: "Thành viên",
    address_label: "Nhãn địa chỉ",
    invalid_voucher: "Voucher không hợp lệ",
    welcome_back: "Chào mừng quay trở lại",
    create_account: "Tạo tài khoản",
    dont_have_account: "Chưa có tài khoản? ",
    already_have_account: "Đã có tài khoản? ",
    sign_up: "Đăng ký",
    sign_in: "Đăng nhập",
    auth_failed: "Lỗi xác thực",
    scan_tap_desc: "Nhấn vào bất kỳ sản phẩm nào để thêm vào giỏ hàng trên thiết bị được kết nối.",
    session: "Phiên",
    storefront_loading: "Đang tải trang cửa hàng...",
    shop_not_found: "Không tìm thấy hồ sơ cửa hàng",
    shop_deactivated: "Cửa hàng của người bán này có thể đã bị tạm ngưng hoặc gỡ bỏ.",
    shopee_mall: "Shopee Mall",
    no_shop_desc: "Chưa có mô tả cửa hàng.",
    chat_with_seller: "Trò chuyện với Người bán",
    no_featured_products: "Chưa có sản phẩm nổi bật nào được chọn.",
    all_store_products: "Tất cả sản phẩm của Cửa hàng",
    no_products_yet: "Cửa hàng này hiện chưa đăng bán sản phẩm nào.",
    wishlist_empty: "Danh sách yêu thích của bạn trống",
    wishlist_empty_desc: "Khám phá các sản phẩm và nhấn vào biểu tượng trái tim để lưu lại những mặt hàng bạn yêu thích.",
    my_wishlist: "Danh sách yêu thích của tôi",
    items_saved: "sản phẩm đã lưu",
    item_saved: "sản phẩm đã lưu",
    live_stream_loading: "Đang tải trình phát Live Stream...",
    live_label: "TRỰC TIẾP",
    viewers: "người xem",
    host: "Người live",
    pinned_deal: "ƯU ĐÃI ĐANG GHIM",
    buy: "Mua",
    rose_gift: "Hoa hồng",
    heart_gift: "Trái tim",
    rocket_gift: "Tên lửa",
    insufficient_coins: "Không đủ số dư xu! Hãy mua sắm thêm để tích lũy.",
    login_to_gift: "Vui lòng đăng nhập để gửi quà tặng ảo!",
    live_bag_title: "Túi đồ Live Stream Đặc Biệt",
    no_live_products: "Không có sản phẩm nào được liên kết với Live Stream.",
    live_comments_title: "Bình luận trực tiếp",
    type_comment: "Nhập bình luận...",
    send_comment: "Gửi",
    gift_rose_desc: "đã gửi tặng Hoa hồng!",
    gift_heart_desc: "đã gửi tặng Trái tim!",
    gift_rocket_desc: "đã gửi tặng Tên lửa!",
    live_welcome: "Chào mừng đến với Stuffy Live Stream! Hãy trò chuyện lịch sự.",
    live_welcome_desc: "Nhấp vào biểu tượng túi mua sắm bên dưới để xem các ưu đãi hot!",
    bot_comment_1: "Sản phẩm này còn hàng không shop?",
    bot_comment_2: "Vừa chốt đơn 2 món xong! Hóng hàng ghê!",
    bot_comment_3: "Cửa hàng có giao ra Hà Nội không ạ?",
    bot_comment_4: "Người bán cực kỳ uy tín nhé mọi người!",
    bot_comment_5: "Live stream này có voucher giảm giá nào không shop?",
    bot_comment_6: "Oa, giảm giá đậm quá!",
    bot_comment_7: "Thiết kế siêu đẹp luôn",
    bot_comment_8: "Đơn vị nào xử lý vận chuyển thế ạ?",
    bot_comment_9: "Ship nhanh cực kỳ, mình nhận hàng rất sớm.",
    origin: "Nơi bán",
    coins: "Xu"
  }
};

export const seedLocalization = async (tenantId = 'default_store') => {
  try {
    const count = await Localization.countDocuments({ tenantId });
    if (count > 0) {
      console.log(`[Seed] Localization collection already contains data for tenant: ${tenantId}`);
      return;
    }

    console.log(`[Seed] Seeding localization data for tenant: ${tenantId}...`);
    const bulkOps = [];

    // Seed English
    for (const [key, value] of Object.entries(translationsSeed.en)) {
      bulkOps.push({
        lang: 'en',
        key,
        value,
        tenantId
      });
    }

    // Seed Vietnamese
    for (const [key, value] of Object.entries(translationsSeed.vi)) {
      bulkOps.push({
        lang: 'vi',
        key,
        value,
        tenantId
      });
    }

    await Localization.insertMany(bulkOps);
    console.log(`[Seed] Successfully seeded ${bulkOps.length} translations key-value pairs.`);
  } catch (error: any) {
    console.error('[Seed] Error seeding localization data:', error.message);
  }
};
